import './globals.css';
import type { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';
// import { useRouter } from 'next/router';
import { Noto_Sans } from 'next/font/google';
import Navbar from './components/Navbar';
import Provider from './components/Provider';


const inter = Noto_Sans({subsets: ['latin'], weight: '400'})

// export async function getStaticProps() {
//   // Simulate fetching page title based on route (replace with your logic)
//   const router = useRouter();
//   const currentPage = router.pathname;
//   let title = "Home";
//   if (currentPage === "/projects") {
//     title = "Projects";
//   }

//   return {
//     props: {
//       metadata: Metadata = {
//         title: `Back-end Web Developer | ${title}`,
//         description: 'Generated by create next app',
//         icons: {
//           icon: "icon.png"
//         }
//       }
//     }
//   }
// }

export const metadata: Metadata = {
  title: 'harsh.dev | Full-Stack & Node.js Developer',
  description: 'Generated by create next app',
  icons: {
    icon: "icon.png"
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} layout`}>
        <Provider>
          <ToastContainer/>
          <Navbar />
          <main className='max-w-6xl mx-auto px-4 sm:px-6 lg:px-4'>
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
